version: '3.8'

services:
  db:
    image: mysql:8.1
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
  api-server:
    build: backend
    ports:
      - "8080:8080"
  ml:
    build: ml
    ports:
      - "50051"